---
- name: create directories
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ path_repos }}"
    - "{{ path_bin }}"

- name: setup rust and rust cli utils
  include_role:  
    name: ../../kali-init/ansible/roles/bootstrap-rust
  vars:
    rust_packages:
      - exa
      - bat
      - tealdeer
      - git-delta

- name: set delta as git default
  blockinfile:
    create: true
    path: "{{ ansible_facts.user_dir }}/.gitconfig"
    block: "{{ lookup('file', '.gitconfig') }}"

########## remysharper: CLI improved ##########
# https://remysharp.com/2018/08/23/cli-improved
###############################################
# prettyping
- name: download prettyping
  get_url: 
    url: "https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping"
    dest: "{{ item.dest }}" 
    mode: 0755
  with_items:
    - {url: "{{ url_prettyping }}", dest: "{{ path_bin }}" }
# ncdu
- name: download ncdu amd64
  unarchive:
    src: "{{ url_ncdu_amd64 }}"
    dest: "{{ path_bin }}"
    remote_src: yes
  when: ansible_architecture == "x86_64"
- name: download ncdu arm64
  unarchive:
    src: "{{ url_ncdu_arm64 }}"
    dest: "{{ path_bin }}"
    remote_src: yes
  when: ansible_architecture == "arm64"
- name: download ncdu arm32
  unarchive:
    src: "{{ url_ncdu_arm32 }}"
    dest: "{{ path_bin }}"
    remote_src: yes
  when: ansible_architecture == "armv7l"
####### END CLI IMPROVED #######

- name: include vim.yaml tasks
  include_tasks: "vim.yaml"

- name: include tmux.yaml tasks
  include_tasks: "tmux.yaml"

- name: include zsh.yaml tasks
  include_tasks: "zsh.yaml"

- name: conditional pentest-utils.yaml tasks
  include_tasks: "pentest-utils.yaml"
  when: pentest_utils