- name: install required apt packages
  include_role: 
    name: ../../kali-init/ansible/roles/bootstrap-apt
  vars:
    apt_packages:
        - tmux

- name: copy config files
  copy: src={{ item }} dest="{{ ansible_facts.user_dir }}/{{ item }}"
  with_items:
    - .tmux.conf

- name: clone TPM (TMUX Plugin Manager) repo
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ ansible_facts.user_dir }}/.tmux/plugins/tpm"
    depth: 1